oneup_flysystem:
    adapters:
        main_adapter:
            googlecloudstorage:
                client: shopsys.google_storage_client
                bucket: shopsys.google_storage_bucket
        local_adapter:
            local:
                directory: "/"

    filesystems:
        main_filesystem:
            adapter: main_adapter
            alias: "main_filesystem"
        local_filesystem:
            adapter: local_adapter
            alias: "local_filesystem"
